Update Catch2 to version 3
Update to the latest version solves the problem with error related to stack
size.

  In file included from /usr/include/signal.h:328,
                   from /symforce/third_party/catch2/include/catch.hpp:8152,
                   from /symforce/third_party/catch2/src/catch_amalgamated.cpp:15:
  /symforce/third_party/catch2/src/catch_amalgamated.cpp:3580:54: error: call to non-'constexpr' function 'long int sysconf(int)'
   3580 | static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
        |                                                      ^~~~~~~~~~~
  In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                   from /usr/include/signal.h:328,
                   from /symforce/third_party/catch2/include/catch.hpp:8152,
                   from /symforce/third_party/catch2/src/catch_amalgamated.cpp:15:
  /usr/include/unistd.h:640:17: note: 'long int sysconf(int)' declared here
    640 | extern long int sysconf (int __name) __THROW;
        |                 ^~~~~~~
  /symforce/third_party/catch2/src/catch_amalgamated.cpp:3633:41: error: size of array 'altStackMem' is not an integral constant-expression
   3633 | char FatalConditionHandler::altStackMem[sigStackSize] = {};